[libffi]
version = "0.0.0"

[OpenSSL]
version = "1.1.1s"

[Python]
version = "3.11.2"
install_host_from_source = true

[Python.win]
install_host_from_source = false

[PyQt]
version = "5.15.2"
installed_modules = []

[PyQt.android]
disabled_features = ["PyQt_Desktop_OpenGL", "PyQt_Printer"]
installed_modules = ["QtCore", "QtGui", "QtNetwork", "QtWidgets",
        "QtAndroidExtras"]

[PyQt3D]
version = "5.15.5"

[PyQtChart]
version = "5.15.5"

[PyQtDataVisualization]
version = "5.15.5"

[PyQtNetworkAuth]
version = "5.15.5"

[PyQtPurchasing]
version = "5.15.5"

[PyQtWebEngine]
version = "5.15.5"

[QScintilla]
version = "2.13.2"

[Qt]
version = "5.15.2"
edition = "opensource"
configure_options = ["-opengl", "desktop", "-no-dbus", "-qt-pcre"]
skip = ["qtactiveqt", "qtconnectivity", "qtdoc", "qtgamepad", "qtlocation",
        "qtmultimedia", "qtnetworkauth", "qtquickcontrols",
        "qtquickcontrols2", "qtremoteobjects", "qtscript", "qtscxml",
        "qtsensors", "qtserialbus", "qtserialport", "qtspeech", "qtsvg",
        "qttools", "qttranslations", "qtwayland", "qtwebchannel",
        "qtwebengine", "qtwebsockets", "qtwebview", "qtxmlpatterns"]

[Qt.android]
install_from_source = false
ssl = "openssl-linked"

[SIP]
version = "12.11.1"
module_name = "PyQt5.sip"
abi_major_version = 12

[zlib]
install_from_source = false

[zlib.win]
version = "1.2.12"
install_from_source = true
static_msvc_runtime = true